version: '3'

services:
  chat:
    image: chat_service
    build:
      context: ./chat
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    deploy:
      replicas: 3

  auth:
    image: auth_service
    build: 
      context: ./auth
    env_file:
      - ./auth/.env
    ports:
      - 8000:8000
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  loadbalancer:
    image: mynginx:latest
    build: 
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      chat:
        condition: service_started
    restart: on-failure


  redis:
    image: redis:latest
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.13-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
  